### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by CyndieKamau** [nyambura00/rust_traits#1]
```rust
fn hi_there(s: &str) -> Option<String> {

    let x = format!("Hey {}! I am Cyndie. Fellow Polkadot rookie! I just wanted to say hi :)", &s);

    Some(x)

}


fn main() {
    let s = "Winnie";

    match hi_there(&s) {

        Some(x) => println!("{}", x),

        None => println!("Oh boy! My Hi message never made it to {} :(", s),

    }
}
```

**Comment by nyambura00** [comment]
Hello Cyndie. Glad to see you building on Polkadot and Rustlang.

How's it going:?

**Comment by CyndieKamau** [comment]
Great! I mean ya know Rustlang is a black hole😂😂 but hey I ain't complaining 💪

**Comment by nyambura00** [comment]
Hehe there is that. 

Though it gets better with time - we keep building and building.

Join Rust Devs Kenya community to connect with fellow Rustaceans:
[Rust Devs Kenya Telegram community](https://t.me/+G8BrYdWiqhNjMWRk)

**Comment by CyndieKamau** [comment]
Yeah actually I'm part of the channel😊
